'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {applySnapshot}=require('../scripts/attach-anidub');
const now=new Date('2026-10-07T12:00:00Z');
const snapshot=()=>({checkedAt:'2026-10-07T00:00:00Z',anime:[{id:1,title:'Example',type:'Series',year:2024}],seasons:[{id:1,anime_id:1,season_name:'Season 1'},{id:2,anime_id:1,season_name:'Season 2'}],dubs:[{anime_id:1,season_id:1,language:'Tamil',platform:'Crunchyroll',status:'Complete',episodes_dubbed:'12'},{anime_id:1,season_id:2,language:'Tamil',platform:'Crunchyroll',status:'Complete',episodes_dubbed:'13'}]});
test('adds explicit Tamil only, no official evidence invented',()=>{const s=snapshot();s.dubs[1].language='Hindi';const r=applySnapshot({anime:[]},s,{now});assert.equal(r.catalog.anime.length,1);const a=r.catalog.anime[0];assert.equal(a.tamilDubConfirmed,true);assert.equal(a.tamilDubVerified,false);assert.equal(a.platforms[0].officialUrl,null);assert.equal(a.seasonDetails.length,1);});
test('official verification and Anime Mirchi report provenance preserved',()=>{const c={anime:[{id:'x',title:'Example',tamilDubVerified:true,platforms:[{name:'Crunchyroll',available:true,tamilDubVerified:true,tamilDubVerificationUrl:'https://example.test/proof',tamilDubReportSource:'Anime Mirchi'}]}]};const r=applySnapshot(c,snapshot(),{now});assert.equal(r.catalog.anime[0].platforms[0].tamilDubVerified,true);assert.equal(r.catalog.anime[0].platforms[0].tamilDubReportSource,'Anime Mirchi');assert.equal(c.anime[0].tamilDubConfirmed,undefined);});
test('exact curated season scope and idempotence',()=>{const c={anime:[{id:'x',title:'Example Season 1',platforms:[]}]},identities={entries:{1:{title:'Example',records:[{id:'x',seasonIds:[1]}]}}};const r=applySnapshot(c,snapshot(),{now,identities});assert.equal(r.catalog.anime[0].seasonDetails.length,1);assert.equal(r.catalog.anime[1].title,'Example Season 2');const r2=applySnapshot(r.catalog,snapshot(),{now,identities});assert.deepEqual(r2.catalog,r.catalog);assert.equal(r2.added.length,0);});
test('ambiguous exact title skips without mutation',()=>{const c={anime:[{id:'x',title:'Example'},{id:'y',title:'EXAMPLE'}]},r=applySnapshot(c,snapshot(),{now});assert.deepEqual(r.catalog.anime,c.anime);assert.match(r.skipped[0],/ambiguous/);});
test('invalid, future and stale snapshots leave catalog unchanged',()=>{const c={anime:[]};for(const s of [null,{...snapshot(),checkedAt:'2027-01-01'},{...snapshot(),checkedAt:'2020-01-01'}])assert.deepEqual(applySnapshot(c,s,{now}).catalog,c);});
test('cross-title season mismatch cannot confirm',()=>{const s=snapshot();s.dubs[0].anime_id=2;s.dubs[1].language='Hindi';assert.equal(applySnapshot({anime:[]},s,{now}).catalog.anime.length,0);});
test('JJK S2 and all directory Tamil rows covered without copying S1 verification',()=>{
 const s=snapshot();s.anime[0].title='Jujutsu Kaisen';const c={anime:[{id:'jk1',title:'JUJUTSU KAISEN Season 1',tamilDubVerified:true,platforms:[{name:'Crunchyroll',available:true,tamilDubVerified:true}]}]};
 const identities={entries:{1:{title:'Jujutsu Kaisen',records:[{id:'jk1',seasonIds:[1]}]}}};const r=applySnapshot(c,s,{now,identities});const a=r.catalog.anime.find(a=>a.title==='Jujutsu Kaisen Season 2');assert.ok(a);assert.equal(a.tamilDubVerified,false);assert.equal(a.platforms[0].tamilDubConfirmed,true);assert.equal(a.seasonDetails[0].rows[0].tamilEpisodes,13);
});
test('visible arc labels kept distinct despite conflicting numeric season indexes',()=>{
 const s=snapshot();s.seasons[0].season_name='Season 4 — Public School Arc';s.seasons[0].season_number=1;s.seasons[1].season_name='Season 5 — Emerald Witch Arc';s.seasons[1].season_number=2;const r=applySnapshot({anime:[]},s,{now});assert.deepEqual(r.catalog.anime[0].seasonDetails.map(r=>r.label),s.seasons.map(r=>r.season_name));
});
