'use strict';
// Tamil-dub-only rule: a catalog record may exist only with real Tamil dub evidence (official manifest/platform proof,
// AniDub India confirmation or official YouTube channel videos). A free-site category page or a third-party lead is
// never enough. LEGACY holds the older third-party-reported records that were already published; it must only shrink.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const LEGACY=new Set(["reported-berserk-of-gluttony-213331", "reported-my-unique-skill-makes-me-op-even-at-level-1-201363", "reported-why-raeliana-ended-up-at-the-duke-s-mansion-205366", "reported-after-school-dice-club-91026", "reported-my-status-as-an-assassin-obviously-exceeds-the-hero-s-284644", "reported-my-clueless-first-friend-214547", "reported-my-hero-academia-vigilantes-280110", "reported-tokyo-ghoul-61374", "reported-easygoing-territory-defense-by-the-optimistic-lord-288589", "reported-pok-mon-concierge-221301", "reported-blue-box-207347", "reported-thunder-3-326119", "reported-chainsmoker-cat-312949", "reported-the-ramparts-of-ice-283428", "reported-fool-night-326247", "reported-ultraman-rising-829402", "reported-lost-in-starlight-1165642", "reported-scarlet-1406657", "reported-as-a-reincarnated-aristocrat-i-ll-use-my-appraisal-skill-to-rise-in-the-world-237150", "reported-let-this-grieving-soul-retire-258579", "reported-paradox-live-the-animation-203045", "reported-the-magical-girl-and-the-evil-lieutenant-used-to-be-archenemies-239764", "reported-ghost-in-the-shell-stand-alone-complex-1095", "reported-jojo-s-bizarre-adventure-steel-ball-run-45790-s6", "reported-even-though-i-m-a-super-timid-noble-girl-i-accepted-the-bet-from-my-cunning-fianc-303060", "reported-black-clover-73223"]);
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','anime.json'),'utf8')).anime;
const qualified=a=>a.tamilDubVerified===true||(a.platforms||[]).some(p=>p.tamilDubVerified===true)||(a.tamilDubConfirmed===true&&a.tamilDubConfirmationSource==='AniDub India')||(Array.isArray(a.youtube)&&a.youtube.length>0);
test('no record is included only because a free site listed it',()=>{const bad=catalog.filter(a=>a.inclusionSource==='free-site-tamil-listing'||a.inclusionSource==='third-party-unconfirmed'||a.tamilDubUnconfirmed===true).map(a=>a.title);assert.deepEqual(bad,[]);});
test('every new record has real Tamil dub evidence',()=>{const bad=catalog.filter(a=>!qualified(a)&&!LEGACY.has(a.id)).map(a=>a.title);assert.deepEqual(bad,[]);});
test('legacy list only contains ids still in the catalog and still lacking proof',()=>{const ids=new Set(catalog.map(a=>a.id));for(const id of LEGACY)if(ids.has(id))assert.equal(qualified(catalog.find(a=>a.id===id)),false,id+' now has proof; drop it from LEGACY');});
